In [2]:
import pandas as pd

In [18]:
def prepare_data(data, time_column = "total_proof_time_ms"):
    data = data.copy()

    data.loc[:, "proof_time_s"] = (data[time_column] / 1000).round(2)

    mask = data["filename"].str.contains("apc000", na=False)
    row = data.loc[mask].drop_duplicates()
    software_proof_time = row["proof_time_s"].squeeze()
    software_proof_time

    data.loc[:, "faster_than_baseline"] = (software_proof_time / data["proof_time_s"]).round(2)
    return data[["filename", "num_segments", "proof_time_s", "faster_than_baseline"]]

# Manual + APC (with recursion)

In [19]:
data = pd.read_csv("latest_nightly/reth/basic_metrics.csv")

In [20]:
prepare_data(data, "total_proof_time_ms")

           filename  num_segments  proof_time_s  faster_than_baseline
0  reth/apc000.json             6        341.19                  1.00
1  reth/apc003.json             5        293.89                  1.16
2  reth/apc010.json             5        274.16                  1.24
3  reth/apc030.json             4        265.54                  1.28
4  reth/apc100.json             3        248.43                  1.37

# Manual + APC (no recursion)

In [21]:
data2 = pd.read_csv("basic_metrics.csv")

In [22]:
prepare_data(pd.concat([data, data2]), "app_proof_time_ms")

               filename  num_segments  proof_time_s  faster_than_baseline
0      reth/apc000.json             6        232.26                  1.00
1      reth/apc003.json             5        195.78                  1.19
2      reth/apc010.json             5        179.28                  1.30
3      reth/apc030.json             4        174.28                  1.33
4      reth/apc100.json             3        157.62                  1.47
0   metrics_apc500.json             1        130.02                  1.79
1  metrics_apc1000.json             1        126.35                  1.84
2  metrics_apc2000.json             1        128.18                  1.81