In [1]:
import pandas as pd

In [2]:
experiments = ["keccak", "sha256", "ecc", "ecrecover", "u256"]

In [3]:
dfs = {experiment: pd.read_csv(f"{experiment}/basic_metrics.csv") for experiment in ["keccak", "sha256", "ecrecover", "u256"]}

In [4]:
# Split ECC into two, affine and projective
ecc_data = pd.read_csv("ecc/basic_metrics.csv")

mask = ecc_data["filename"].str.contains("affine|manual", case=False, na=False)
dfs["ecc_affine"] = ecc_data.loc[mask]

mask = ecc_data["filename"].str.contains("projective|manual", case=False, na=False)
dfs["ecc_projective"] = ecc_data.loc[mask]

In [5]:
all_data = {}

for experiment, data in dfs.items():
    data = data.copy()

    data.loc[:, "proof_time_s"] = (data["total_proof_time_ms"] / 1000).round(2)

    mask = data["filename"].str.contains("apc000", na=False)
    row = data.loc[mask].drop_duplicates()
    software_proof_time = row["proof_time_s"].squeeze()
    software_proof_time
    
    mask = data["filename"].str.contains("manual", na=False)
    row = data.loc[mask].drop_duplicates()
    manual_proof_time = row["proof_time_s"].squeeze()
    manual_proof_time

    data.loc[:, "faster_than_software"] = (software_proof_time / data["proof_time_s"]).round(2)
    data.loc[:, "slower_than_manual"]   = (data["proof_time_s"] / manual_proof_time).round(2)

    all_data[experiment] = data[["filename", "num_segments", "proof_time_s",
                                 "faster_than_software", "slower_than_manual"]]

In [6]:
all_data["keccak"]

,filename,num_segments,proof_time_s,faster_than_software,slower_than_manual
0,apc000/metrics.json,20,347.80,1.00,9.03
1,apc003/metrics.json,1,30.60,11.37,0.79
2,apc010/metrics.json,1,30.65,11.35,0.80
3,apc030/metrics.json,1,31.15,11.17,0.81
4,manual/metrics.json,2,38.51,9.03,1.00

In [7]:
all_data["sha256"]

,filename,num_segments,proof_time_s,faster_than_software,slower_than_manual
0,apc000/metrics.json,17,279.06,1.00,17.70
1,apc003/metrics.json,1,48.30,5.78,3.06
2,apc010/metrics.json,1,42.26,6.60,2.68
3,apc030/metrics.json,1,51.93,5.37,3.29
4,manual/metrics.json,1,15.77,17.70,1.00

In [8]:
all_data["ecc_projective"]

,filename,num_segments,proof_time_s,faster_than_software,slower_than_manual
5,manual/metrics.json,1,13.41,28.26,1.00
6,projective-apc000/metrics.json,20,379.00,1.00,28.26
7,projective-apc003/metrics.json,5,157.59,2.40,11.75
8,projective-apc010/metrics.json,4,152.98,2.48,11.41
9,projective-apc030/metrics.json,2,129.21,2.93,9.64
10,projective-apc100/metrics.json,2,134.71,2.81,10.05

In [9]:
all_data["ecc_affine"]

,filename,num_segments,proof_time_s,faster_than_software,slower_than_manual
0,affine-hint-apc000/metrics.json,8,150.78,1.00,11.24
1,affine-hint-apc003/metrics.json,8,138.90,1.09,10.36
2,affine-hint-apc010/metrics.json,3,87.79,1.72,6.55
3,affine-hint-apc030/metrics.json,1,51.40,2.93,3.83
4,affine-hint-apc100/metrics.json,1,64.92,2.32,4.84
5,manual/metrics.json,1,13.41,11.24,1.00

In [10]:
all_data["ecrecover"]

,filename,num_segments,proof_time_s,faster_than_software,slower_than_manual
0,apc000/metrics.json,7,132.23,1.00,9.23
1,apc003/metrics.json,4,111.15,1.19,7.76
2,apc010/metrics.json,2,78.52,1.68,5.48
3,apc030/metrics.json,1,47.29,2.80,3.30
4,apc100/metrics.json,1,61.26,2.16,4.28
5,manual/metrics.json,1,14.32,9.23,1.00

In [11]:
all_data["u256"]

,filename,num_segments,proof_time_s,faster_than_software,slower_than_manual
0,apc000/metrics.json,12,220.25,1.00,1.71
1,apc003/metrics.json,4,100.95,2.18,0.79
2,apc010/metrics.json,1,41.53,5.30,0.32
3,apc030/metrics.json,1,43.63,5.05,0.34
4,manual/metrics.json,8,128.50,1.71,1.00